private let _namesString = """
com.ask.Alphazap
uk.gov.Temp
com.netscape.Latlux
com.tumblr.Tres-Zap
com.dagondesign.Sonair
com.vinaora.Bamity
com.samsung.Ventosanzap
com.deviantart.Aerified
com.bizjournals.Zamit
com.example.Greenlam
gov.cdc.Flexidy
uk.gov.Stim
com.vk.Zoolab
edu.msu.Cardify
com.taobao.Y-find
com.artisteer.Namfix
org.archive.HomeIng
com.newyorker.Aerified
com.ehow.Voltsillam
io.soup.Subin
gov.usa.Gembucket
ru.liveinternet.Viva
edu.berkeley.Gembucket
com.ifeng.Zaam-Dox
gov.ed.Y-Solowarm
com.opera.Sonair
com.hao123.Zamit
com.sohu.Transcof
ca.google.Hatity
net.clickbank.Alphazap
it.tuttocitta.Solarbreeze
io.pen.Andalax
com.weebly.Sonair
com.sogou.Kanlam
com.nbcnews.Bamity
com.shutterfly.Sonair
com.comsenz.Konklux
edu.harvard.Alphazap
com.diigo.Holdlamis
com.canalblog.Voltsillam
com.sciencedaily.Greenlam
com.hubpages.Tempsoft
edu.si.Lotstring
com.shutterfly.Zaam-Dox
com.about.Tres-Zap
gov.usda.Transcof
com.mapquest.Toughjoyfax
edu.msu.Zamit
gov.cdc.Alpha
com.businesswire.Stronghold
com.reddit.Biodex
com.bloglines.It
edu.unc.Subin
com.sbwire.Overhold
com.vk.Bitwolf
ru.ucoz.Alpha
com.mashable.Tresom
jp.geocities.Stim
ch.admin.Duobam
uk.co.telegraph.Regrant
com.instagram.Flexidy
fr.google.Mat Lam Tam
com.topsy.Bigtax
org.altervista.Vagram
gl.goo.Vagram
edu.unc.Lotlux
com.blogspot.Veribet
gov.ftc.Zaam-Dox
com.devhub.Stronghold
com.hostgator.Tres-Zap
com.dropbox.Ronstring
com.bigcartel.Vagram
edu.ucsd.Latlux
jp.co.amazon.Veribet
com.theglobeandmail.Konklab
com.nytimes.Opela
com.hugedomains.Sub-Ex
com.baidu.Transcof
net.furl.Tin
jp.shop-pro.Alphazap
hk.com.google.Veribet
com.jiathis.Alpha
com.imgur.Voyatouch
com.omniture.Bitchip
es.google.Latlux
com.apple.Fintone
net.behance.Pannier
com.bravesites.Pannier
com.devhub.Alphazap
vu.de.Voltsillam
edu.cmu.Zathin
jp.ne.so-net.Ronstring
com.ezinearticles.Bitwolf
com.wp.Asoka
com.businessinsider.Konklux
com.nifty.Tampflex
ru.odnoklassniki.Solarbreeze
gd.is.Solarbreeze
uk.ac.cam.Y-find
br.com.google.Fintone
com.blogger.Bitchip
edu.cornell.Zamit
ru.vkontakte.Hatity
org.simplemachines.Konklux
nl.google.Stim
au.gov.nsw.Vagram
au.gov.nsw.Tin
com.wiley.Holdlamis
jp.japanpost.Konklab
edu.mit.Hatity
com.bloglines.Temp
com.mysql.Sub-Ex
com.ezinearticles.Ventosanzap
com.woothemes.Bytecard
ru.odnoklassniki.Pannier
com.naver.Gembucket
pl.home.Sonair
com.twitter.Konklux
edu.virginia.Sonair
nl.google.Holdlamis
com.dedecms.Cardguard
edu.si.Redhold
com.apple.Zathin
edu.upenn.Prodder
uk.nhs.Overhold
jp.i2i.Regrant
uk.co.guardian.Zaam-Dox
fr.unblog.Bytecard
com.pinterest.Fintone
jp.shop-pro.Stim
au.com.google.Alphazap
com.smugmug.Asoka
gov.hhs.Transcof
com.instagram.Wrapsafe
com.zimbio.Greenlam
de.amazon.Overhold
gov.census.Bytecard
com.networksolutions.Daltfresh
gov.irs.Rank
uk.nhs.Zaam-Dox
com.howstuffworks.Aerified
uk.co.google.Redhold
com.usnews.Greenlam
com.nymag.Cookley
de.t-online.Zamit
com.answers.Redhold
com.washingtonpost.Gembucket
com.bloglovin.Konklux
hk.com.google.Stringtough
uk.ac.cam.Home Ing
com.tripadvisor.Y-find
jp.co.google.Regrant
com.weebly.Bytecard
ru.narod.Duobam
ru.mail.Namfix
uk.nhs.Regrant
net.comcast.Tampflex
com.sitemeter.Asoka
cn.com.sina.Span
com.sphinn.Tempsoft
com.photobucket.Span
ly.ow.Alphazap
com.fotki.Veribet
com.engadget.Cardify
com.businesswire.Namfix
com.sitemeter.Sonair
com.eventbrite.Opela
br.com.uol.Bamity
edu.umn.Y-find
com.domainmarket.Vagram
com.time.Keylex
com.elegantthemes.Ronstring
gov.ed.Subin
com.spotify.Trippledex
com.ted.Flowdesk
net.ovh.Tres-Zap
com.zdnet.Overhold
edu.nyu.Stim
org.archive.Tin
com.netvibes.Zaam-Dox
com.sitemeter.Zaam-Dox
com.geocities.Home Ing
com.businessinsider.Aerified
com.typepad.Greenlam
edu.columbia.Tin
com.deviantart.Mat Lam Tam
gov.hud.Fix San
de.t-online.Biodex
io.github.Trippledex
com.domainmarket.Y-find
com.flickr.Fintone
edu.umn.Keylex
com.yahoo.Voyatouch
com.xinhuanet.Stronghold
com.ibm.Mat Lam Tam
com.addthis.Alphazap
com.shinystat.Sonair
com.stumbleupon.Bitwolf
au.com.google.Alphazap
com.quantcast.Konklux
com.chron.Trippledex
com.wordpress.Daltfresh
com.bigcartel.Wrapsafe
jp.shop-pro.Flexidy
br.com.google.Cardify
com.ft.Tres-Zap
uk.co.amazon.Fix San
com.csmonitor.Flexidy
com.businessinsider.Redhold
com.weibo.Stringtough
jp.japanpost.Keylex
com.cbslocal.Stim
com.statcounter.Hatity
com.chron.Treeflex
com.blogtalkradio.Matsoft
gov.fda.Biodex
jp.jugem.Voltsillam
com.booking.Alphazap
org.mozilla.Namfix
com.paypal.Mat Lam Tam
com.tripod.Zathin
jp.shop-pro.Regrant
com.purevolume.Lotstring
com.howstuffworks.Otcom
uk.co.telegraph.Zaam-Dox
com.comsenz.Home Ing
com.dagondesign.Overhold
gov.state.Zoolab
com.ibm.Rank
us.icio.Bigtax
au.org.auda.Prodder
com.ask.Bitchip
co.g.Keylex
com.mac.Flowdesk
org.unesco.Bitchip
edu.stanford.Y-find
ru.google.Voltsillam
de.t-online.Otcom
com.sun.Veribet
gov.nasa.Voyatouch
com.oakley.Bitwolf
au.gov.nsw.Pannier
nl.google.Voyatouch
edu.si.Matsoft
com.howstuffworks.Transcof
uk.co.guardian.Duobam
com.dedecms.Temp
edu.princeton.Regrant
com.squidoo.Y-Solowarm
edu.umich.Regrant
com.moonfruit.Namfix
com.example.Y-find
com.mediafire.Mat Lam Tam
edu.unc.Stronghold
com.bluehost.Gembucket
com.bing.Cardguard
com.alibaba.Lotlux
uk.co.amazon.Bitwolf
com.sphinn.Zaam-Dox
org.creativecommons.Fix San
com.blogspot.Ventosanzap
com.tripadvisor.Flexidy
org.w3.Opela
com.ifeng.Bigtax
org.creativecommons.Biodex
jp.ne.biglobe.Transcof
pl.google.Fix San
com.washingtonpost.Regrant
com.merriam-webster.Sonair
de.google.Subin
fr.unblog.Bamity
org.bbb.Konklab
eu.europa.Bytecard
jp.co.rakuten.Overhold
edu.yale.Zamit
ru.yandex.Bitchip
com.nydailynews.Vagram
com.wsj.Veribet
uk.co.independent.Duobam
ca.google.Ronstring
com.printfriendly.Zontrax
com.elegantthemes.Mat Lam Tam
com.aol.Pannier
com.nifty.Zathin
com.wsj.Bamity
org.archive.Veribet
gov.cdc.Cardguard
be.youtu.Span
com.netscape.Redhold
ru.ucoz.Zaam-Dox
edu.columbia.Bigtax
com.nytimes.Ronstring
org.wordpress.Voyatouch
com.geocities.Prodder
com.latimes.Sonair
cn.gov.miitbeian.Namfix
com.accuweather.Kanlam
uk.co.thetimes.Solarbreeze
jp.geocities.Alphazap
gov.nps.Keylex
cn.com.china.Lotstring
gov.usda.Tin
com.pcworld.Toughjoyfax
gov.fda.Sonsing
com.cargocollective.Bytecard
cn.360.Vagram
com.reference.Otcom
com.intel.Opela
com.booking.Duobam
jp.jugem.Home Ing
hk.com.google.Namfix
com.angelfire.Tin
jp.ne.hatena.Lotstring
com.hugedomains.Pannier
com.amazonaws.Fix San
com.delicious.Bigtax
com.ucoz.Flowdesk
com.xing.Aerified
com.rediff.Cookley
org.w3.Kanlam
de.1und1.Voyatouch
com.usnews.Transcof
com.multiply.Aerified
uk.co.thetimes.Job
ca.google.Y-Solowarm
com.networksolutions.Stronghold
com.hc360.Trippledex
edu.washington.Cardify
com.shareasale.Veribet
com.parallels.Duobam
cz.phoca.Y-Solowarm
com.nifty.Trippledex
gov.nasa.Fintone
uk.co.webeden.Cardguard
nl.google.Sonsing
com.nifty.Solarbreeze
com.sphinn.Fintone
net.ovh.Sonsing
com.deliciousdays.Span
com.devhub.Fix San
com.buzzfeed.Tresom
com.diigo.Ventosanzap
com.spotify.Bamity
com.nymag.Biodex
gov.ed.Keylex
mil.army.Matsoft
com.dedecms.Latlux
com.bandcamp.Span
com.godaddy.Wrapsafe
com.alibaba.Latlux
com.qq.Konklux
gov.epa.Lotstring
com.phpbb.Daltfresh
mil.army.Trippledex
com.nytimes.Cardguard
uk.co.dailymail.Stringtough
net.a8.Bamity
com.prnewswire.Stim
com.theglobeandmail.Bitwolf
com.youku.Opela
us.imageshack.Bigtax
com.skype.Treeflex
com.cafepress.Asoka
net.discuz.Veribet
net.furl.Fix San
com.answers.Sonair
com.parallels.Y-Solowarm
hk.com.google.Cardguard
com.bandcamp.Mat Lam Tam
net.comcast.Tresom
com.slate.Ronstring
com.squidoo.Tin
edu.cornell.Tresom
com.weibo.Kanlam
org.mozilla.Konklab
com.bloglines.Greenlam
jp.ne.hatena.Vagram
de.e-recht24.Solarbreeze
com.sogou.Wrapsafe
com.ft.Tresom
gov.dot.Regrant
info.aboutads.Pannier
com.moonfruit.Zoolab
com.usatoday.Keylex
com.merriam-webster.Bitchip
au.com.google.Toughjoyfax
net.php.Trippledex
com.list-manage.Toughjoyfax
com.cafepress.Lotlux
jp.japanpost.Job
fr.google.Mat Lam Tam
com.answers.Namfix
gov.house.Andalax
com.godaddy.Biodex
com.go.Toughjoyfax
com.hugedomains.Aerified
gov.ftc.Gembucket
cn.com.sina.Mat Lam Tam
uk.co.amazon.Alphazap
org.redcross.Job
uk.co.bbc.Stringtough
com.sbwire.Cardify
org.unicef.Gembucket
com.marriott.Konklux
com.globo.Flexidy
com.wix.Y-Solowarm
uk.co.dailymail.Quo Lux
gov.senate.Aerified
com.ezinearticles.Wrapsafe
com.ibm.Regrant
au.org.auda.It
uk.co.webeden.Lotlux
net.sourceforge.Tresom
com.cnet.Job
jp.i2i.Flexidy
pl.home.Lotstring
com.yellowbook.Solarbreeze
org.drupal.Lotlux
com.sbwire.Bitwolf
com.disqus.Ventosanzap
com.lulu.Pannier
com.livejournal.Greenlam
com.huffingtonpost.Alphazap
com.meetup.Ronstring
com.ask.Ventosanzap
uk.co.123-reg.Y-find
com.ifeng.Transcof
com.reddit.Voltsillam
com.vk.Tampflex
ru.rambler.Cookley
com.xrea.Trippledex
org.wikimedia.Daltfresh
com.printfriendly.Job
com.lulu.Otcom
edu.stanford.Y-find
com.time.Redhold
cz.phoca.It
pl.google.Viva
com.posterous.Konklux
com.walmart.Fintone
com.imgur.Domainer
eu.europa.Pannier
la.51.Cardify
com.discovery.Stronghold
gov.epa.Temp
gov.usgs.Holdlamis
com.chron.It
edu.washington.Gembucket
com.techcrunch.Tresom
jp.ameblo.Ventosanzap
com.ycombinator.Prodder
org.npr.Temp
com.lycos.Regrant
org.simplemachines.Biodex
com.bloglines.Holdlamis
com.naver.Bigtax
com.elpais.Opela
com.statcounter.Cardguard
com.baidu.Tresom
com.gravatar.Tempsoft
com.twitpic.Trippledex
com.newsvine.Zontrax
com.xinhuanet.Prodder
com.cyberchimps.Tin
com.tinyurl.Tampflex
com.latimes.Y-find
com.netscape.Bigtax
org.creativecommons.Tresom
com.bizjournals.Bytecard
org.opensource.Bitwolf
com.parallels.Aerified
cn.com.people.Viva
gov.fema.Konklux
com.bloomberg.Wrapsafe
gov.usgs.Cardify
com.squidoo.Stronghold
net.seesaa.Fintone
com.nifty.Mat Lam Tam
com.issuu.Fintone
com.aol.Sonsing
com.wordpress.Stringtough
fr.pagesperso-orange.Domainer
ru.mail.Zontrax
com.blogs.Sonsing
com.comsenz.Voyatouch
com.hao123.Keylex
com.ibm.Otcom
edu.unc.Bigtax
com.wired.Domainer
com.vinaora.Daltfresh
com.techcrunch.Lotlux
io.soup.Cardguard
uk.gov.Fix San
com.webs.Kanlam
me.flavors.Toughjoyfax
com.wikispaces.Hatity
com.tripadvisor.Subin
edu.unc.Transcof
com.booking.Kanlam
com.geocities.Stringtough
edu.yale.Pannier
com.devhub.Biodex
it.tuttocitta.Fix San
com.delicious.Zoolab
gov.state.Lotstring
com.naver.Tampflex
com.paypal.Rank
com.skype.Sonsing
de.t-online.Andalax
cn.com.china.Tampflex
tv.ustream.Asoka
com.elpais.Lotstring
com.tripadvisor.Transcof
com.spotify.Biodex
gl.goo.Vagram
com.nymag.Veribet
com.omniture.Konklux
com.cocolog-nifty.Tampflex
org.altervista.Viva
jp.exblog.Cardguard
it.google.Zamit
ru.odnoklassniki.Home Ing
edu.umn.Lotstring
com.tripadvisor.Alpha
it.tuttocitta.Rank
gl.goo.Hatity
com.mayoclinic.Stronghold
com.youku.Bitwolf
com.chron.Domainer
net.comcast.Cardify
com.linkedin.Wrapsafe
edu.upenn.Job
com.cbslocal.Voyatouch
com.jimdo.Matsoft
com.lycos.Hatity
it.tuttocitta.Zontrax
org.opensource.Zathin
com.walmart.Subin
com.topsy.Konklab
edu.berkeley.Cookley
edu.upenn.Bytecard
uk.co.thetimes.Holdlamis
org.drupal.Bigtax
com.indiegogo.Holdlamis
com.comsenz.It
com.twitpic.Domainer
com.yelp.Redhold
com.wsj.Temp
com.theatlantic.Cookley
be.youtu.Fix San
com.macromedia.Zathin
ru.google.Alpha
com.wired.Zoolab
edu.unc.Overhold
gov.epa.Subin
com.yelp.Flowdesk
com.wix.Voyatouch
com.mac.Fixflex
com.techcrunch.Viva
au.com.smh.Voyatouch
au.gov.nsw.Biodex
com.samsung.Stringtough
com.yahoo.Tres-Zap
com.walmart.Transcof
com.sbwire.Bitwolf
com.slate.Tresom
jp.i2i.Stringtough
cn.com.sina.Pannier
io.soup.Solarbreeze
edu.arizona.Otcom
com.nifty.Konklab
com.cnn.Rank
com.ucoz.Sonair
com.rediff.Stronghold
jp.exblog.Flowdesk
com.facebook.Fix San
uk.co.timesonline.Asoka
au.com.google.Bytecard
com.elegantthemes.Wrapsafe
com.zimbio.Mat Lam Tam
com.boston.Cardify
com.sbwire.Treeflex
uk.co.thetimes.Opela
ru.yandex.Sonair
de.google.Redhold
com.xing.Bitwolf
com.wunderground.Keylex
au.com.google.Home Ing
com.csmonitor.Lotlux
jp.geocities.Span
cn.google.Viva
com.digg.Holdlamis
com.elpais.Zaam-Dox
de.t-online.Regrant
com.tinyurl.Flowdesk
hk.com.google.Lotstring
com.hostgator.Y-find
net.jalbum.Zontrax
com.zimbio.Sonsing
de.spiegel.Cardguard
com.shutterfly.Y-Solowarm
com.sun.Fintone
com.blogspot.Toughjoyfax
com.hp.Voltsillam
com.instagram.Namfix
com.oakley.Zontrax
au.gov.nsw.It
edu.upenn.Stringtough
com.nymag.Alphazap
com.over-blog.Job
gl.goo.Opela
com.xing.Sub-Ex
nl.google.Prodder
org.redcross.Treeflex
com.aol.Sonair
vu.de.Regrant
com.smugmug.Wrapsafe
eu.europa.Fix San
com.quantcast.Prodder
com.wufoo.Otcom
com.lycos.Voltsillam
com.dell.Konklab
org.joomla.Matsoft
org.archive.Fixflex
com.washingtonpost.Span
ru.odnoklassniki.Zontrax
com.acquirethisname.Andalax
com.nationalgeographic.Hatity
com.bizjournals.Hatity
com.cbslocal.Tres-Zap
mil.army.Namfix
com.wordpress.Overhold
edu.ucla.Solarbreeze
com.linkedin.Home Ing
com.comsenz.Zoolab
org.unicef.Transcof
com.diigo.Quo Lux
org.mozilla.Duobam
org.slashdot.Subin
com.macromedia.Pannier
com.ask.Prodder
com.webmd.Latlux
com.bizjournals.Voyatouch
com.wordpress.Cookley
com.freewebs.Tampflex
gov.va.Quo Lux
uk.co.amazon.Prodder
com.alibaba.Regrant
com.lulu.Vagram
com.hexun.Regrant
gov.nih.Stronghold
au.gov.nsw.Overhold
com.marketwatch.Voltsillam
com.icq.Opela
com.hc360.Flowdesk
jp.co.rakuten.Tres-Zap
com.seattletimes.Rank
edu.virginia.Fixflex
com.mashable.Matsoft
ru.narod.Quo Lux
br.com.google.Quo Lux
de.spiegel.Ronstring
com.blogspot.Duobam
uk.co.guardian.Zontrax
au.com.smh.Ronstring
com.surveymonkey.Otcom
tv.ustream.Regrant
com.ask.Flowdesk
com.elpais.Andalax
edu.tamu.Viva
net.ovh.Zontrax
gl.goo.Y-Solowarm
me.flavors.Holdlamis
edu.unc.Tampflex
cz.phoca.Keylex
com.walmart.Temp
com.chicagotribune.Cardify
com.xing.Tin
com.lycos.Alphazap
net.earthlink.Konklab
org.prlog.Redhold
com.icq.Trippledex
pl.google.Temp
edu.mit.Zoolab
com.zdnet.Ronstring
com.merriam-webster.Alpha
com.nymag.Aerified
com.webnode.Veribet
jp.or.plala.Redhold
com.newyorker.Zoolab
com.cyberchimps.Span
com.nba.Lotstring
com.intel.Y-find
net.jalbum.Tresom
com.vistaprint.Redhold
com.newyorker.Tres-Zap
gl.goo.Lotstring
co.t.Sonsing
com.netscape.Domainer
com.vk.Treeflex
com.linkedin.Pannier
uk.co.webeden.Voltsillam
com.ucoz.Alpha
com.sun.Otcom
gov.house.Ventosanzap
com.wordpress.Otcom
com.geocities.Hatity
org.unesco.Temp
com.tripod.Greenlam
edu.ucsd.Home Ing
com.xrea.Namfix
com.shareasale.Lotlux
gov.house.Home Ing
com.mlb.Cardguard
com.diigo.Asoka
com.about.Aerified
com.mediafire.Span
net.seesaa.Hatity
com.cyberchimps.Biodex
com.tinypic.Zontrax
edu.msu.Domainer
org.npr.Fintone
com.booking.Stringtough
uk.co.123-reg.Tres-Zap
com.blinklist.Tres-Zap
gov.nih.Regrant
com.hao123.Subin
uk.co.google.Hatity
com.imgur.Trippledex
com.mysql.Flowdesk
ly.ow.Zoolab
net.cpanel.Tampflex
edu.utexas.Hatity
edu.harvard.Hatity
com.chicagotribune.Cardguard
com.tmall.Redhold
gov.usa.Namfix
com.deliciousdays.Hatity
com.chron.Flexidy
com.amazon.It
com.wp.Subin
com.mayoclinic.Wrapsafe
uk.nhs.Asoka
com.foxnews.Overhold
com.opera.Duobam
gov.cdc.Stim
com.bloglines.Trippledex
edu.harvard.Temp
com.scientificamerican.Cookley
com.elpais.Bytecard
com.yellowpages.Tresom
com.tripod.Hatity
com.chicagotribune.Opela
com.histats.Cardguard
com.cbslocal.Zoolab
com.google.Regrant
com.freewebs.Toughjoyfax
com.ifeng.Zamit
com.howstuffworks.Hatity
cn.google.Temp
com.twitpic.Treeflex
org.archive.Latlux
com.eventbrite.Sonsing
fr.free.Namfix
com.quantcast.Biodex
com.github.Latlux
ch.admin.Matsoft
com.elpais.Tresom
com.prnewswire.Holdlamis
net.themeforest.Gembucket
com.qq.Tempsoft
com.icq.Redhold
com.sogou.Job
tv.ustream.Keylex
com.dagondesign.Voyatouch
com.weebly.Voltsillam
com.taobao.Cardguard
com.cisco.Ventosanzap
com.list-manage.Vagram
uk.co.google.Cardify
uk.nhs.Tempsoft
it.google.Tresom
com.ihg.Zaam-Dox
org.npr.Zamit
com.phpbb.Stronghold
cn.gov.miitbeian.Pannier
net.slideshare.Opela
com.walmart.Matsoft
jp.ne.hatena.Lotstring
com.netlog.Alphazap
com.yelp.Y-find
com.theatlantic.Job
com.theatlantic.Vagram
com.reverbnation.Temp
com.chicagotribune.Tempsoft
com.wired.Opela
com.histats.Subin
de.1und1.Tresom
gov.senate.Aerified
org.unesco.Namfix
uk.co.timesonline.Sub-Ex
com.rediff.Stringtough
edu.ucla.Stronghold
com.delicious.Zamit
ru.yandex.Viva
com.fastcompany.Ventosanzap
com.addthis.Stronghold
com.discovery.Zoolab
ru.rambler.Biodex
ru.ucoz.Home Ing
com.samsung.Solarbreeze
com.fc2.Tampflex
com.purevolume.Solarbreeze
com.geocities.Y-Solowarm
au.gov.oaic.Stringtough
com.hibu.Cardify
com.bloglovin.Transcof
edu.umn.Lotstring
com.shinystat.Regrant
com.devhub.Rank
com.netscape.Vagram
uk.nhs.Flexidy
com.msn.Lotstring
com.lycos.Tempsoft
gov.usa.Redhold
cz.toplist.Flexidy
com.answers.Temp
com.qq.Redhold
us.imageshack.Toughjoyfax
edu.si.Stim
jp.i2i.Tin
com.chron.Bamity
com.foxnews.Bitchip
com.lulu.Temp
com.cloudflare.Redhold
uk.nhs.Cookley
fr.free.Alpha
uk.co.guardian.Namfix
com.jimdo.Aerified
com.omniture.Opela
uk.co.amazon.Overhold
com.bravesites.Opela
com.smugmug.Stim
org.altervista.Treeflex
com.nba.Span
com.yelp.Voltsillam
com.cisco.Ronstring
com.youku.Quo Lux
com.sohu.Gembucket
com.over-blog.Ventosanzap
com.mediafire.Tresom
org.bbb.Zathin
com.zimbio.Tresom
jp.co.amazon.Namfix
pl.home.Temp
com.alibaba.Cardify
com.weebly.Flexidy
com.cafepress.Zontrax
tv.ustream.Zaam-Dox
com.mtv.Flexidy
net.comcast.Opela
com.devhub.Treeflex
com.nature.Ronstring
uk.co.guardian.Zaam-Dox
jp.ameblo.Zaam-Dox
com.hugedomains.Ventosanzap
gov.nih.Mat Lam Tam
cz.phoca.Fintone
com.purevolume.Latlux
com.biblegateway.Tin
com.sitemeter.Keylex
jp.or.plala.Stim
ru.odnoklassniki.Home Ing
ru.yandex.Gembucket
com.statcounter.Cardify
com.answers.Quo Lux
com.live.Transcof
it.paginegialle.Viva
com.cnet.Stronghold
com.tinyurl.Trippledex
edu.berkeley.Bamity
com.printfriendly.Alpha
com.oakley.It
fr.unblog.Fintone
com.springer.Regrant
jp.ne.so-net.Kanlam
com.nifty.Redhold
fm.last.Trippledex
com.nature.Pannier
com.slate.Kanlam
jp.exblog.Subin
com.businessweek.Trippledex
com.com.Aerified
com.xinhuanet.Zoolab
org.unicef.Tin
com.disqus.Voyatouch
com.vk.Ronstring
com.weebly.Opela
de.e-recht24.Otcom
de.amazon.Veribet
com.naver.Stringtough
edu.psu.Tresom
com.cloudflare.Pannier
tv.ustream.Asoka
com.ucoz.Sonsing
com.hc360.Daltfresh
ru.rambler.Trippledex
com.reverbnation.Y-Solowarm
gov.hhs.Bigtax
com.1688.Span
com.sitemeter.Biodex
com.comsenz.Tempsoft
me.about.Solarbreeze
ru.liveinternet.Voltsillam
com.homestead.Rank
cn.com.people.Quo Lux
com.myspace.Span
uk.ac.ox.Kanlam
com.ihg.Flexidy
com.soundcloud.Treeflex
com.blogs.Flexidy
de.amazon.Redhold
com.seattletimes.Bytecard
net.furl.Lotstring
com.marketwatch.Lotlux
com.arstechnica.Sub-Ex
com.opera.Ventosanzap
gov.dot.Namfix
jp.co.yahoo.Cookley
net.clickbank.Tres-Zap
com.shareasale.Tempsoft
uk.co.timesonline.Matsoft
com.nymag.Y-find
com.blogs.Zathin
com.skyrock.Cardify
org.unesco.Cardguard
edu.ucla.Zamit
net.jalbum.Fixflex
com.taobao.Vagram
gov.usda.Voltsillam
com.canalblog.Konklux
edu.illinois.Fixflex
uk.co.independent.Domainer
edu.msu.Transcof
com.mac.Flexidy
br.com.uol.Flowdesk
gov.hhs.Prodder
com.cisco.Fintone
com.elegantthemes.Gembucket
com.aol.Sonair
com.bloglines.Zontrax
org.w3.Greenlam
com.reference.Zathin
com.salon.Kanlam
es.google.Vagram
com.reference.Alpha
jp.co.infoseek.Gembucket
com.angelfire.Span
com.latimes.Gembucket
com.xrea.Veribet
ru.ucoz.Y-Solowarm
com.ehow.Lotstring
org.w3.Alphazap
org.pbs.Tres-Zap
com.meetup.It
com.mashable.Stronghold
es.google.Domainer
de.google.Domainer
com.digg.Sonair
ca.cbc.Alphazap
com.theglobeandmail.Matsoft
com.economist.Zathin
com.blogger.Namfix
it.paginegialle.Regrant
com.sohu.Zoolab
com.weibo.Viva
uk.gov.Bamity
com.squarespace.Viva
nl.google.Namfix
com.ask.Ventosanzap
br.com.uol.Alphazap
jp.geocities.Transcof
com.mac.Latlux
com.quantcast.Opela
io.pen.Alphazap
com.twitter.Bytecard
org.unesco.Bigtax
com.weibo.Overhold
com.typepad.Gembucket
nl.google.Pannier
jp.co.rakuten.Wrapsafe
com.cbsnews.Pannier
com.weather.Pannier
com.chron.Greenlam
com.canalblog.Asoka
gov.usgs.Rank
jp.ne.so-net.Trippledex
com.over-blog.Flowdesk
gov.house.Aerified
com.godaddy.Asoka
"""

struct TaskName {
  private init() {
    names = _namesString.components(separatedBy: .whitespacesAndNewlines)
  }

  let names: [String]

  public func generate() -> String {
    return names[Int.random(in: 0 ..< names.count)]
  }

  public static let shared = TaskName()
}
